
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gabri
 */
public class AlterarFuncionarioBeneficiario extends javax.swing.JFrame {

    /**
     * Creates new form FuncionarioBeneficiario
     */
    public AlterarFuncionarioBeneficiario() {
        initComponents();
    }
    public AlterarFuncionarioBeneficiario(String fknome, String fkben, String fkemp, String valor) {
        initComponents();
          txtNomeFuncionario.setText(fknome);
          txtNomeBeneficio.setText(fkben);
          txtNomeEmpresa.setText(fkemp);
          txtValorBeneficio.setText(valor);
          
          txtNomeFuncionario.setEnabled(false);
          txtNomeEmpresa.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeBeneficiario = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        lblNomeBeneficio = new javax.swing.JLabel();
        txtNomeBeneficio = new javax.swing.JTextField();
        lblNomeEmpresa = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValorBeneficio = new javax.swing.JTextField();
        btnAlterarBeneficio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar benefícios do funcionário");
        getContentPane().setLayout(null);

        lblNomeBeneficiario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeBeneficiario.setText("Nome do funcionario:");
        getContentPane().add(lblNomeBeneficiario);
        lblNomeBeneficiario.setBounds(20, 110, 150, 30);
        getContentPane().add(txtNomeFuncionario);
        txtNomeFuncionario.setBounds(170, 110, 140, 30);

        lblNomeBeneficio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeBeneficio.setText("Nome do benefício:");
        getContentPane().add(lblNomeBeneficio);
        lblNomeBeneficio.setBounds(30, 150, 140, 30);
        getContentPane().add(txtNomeBeneficio);
        txtNomeBeneficio.setBounds(170, 150, 140, 30);

        lblNomeEmpresa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeEmpresa.setText("Nome da empresa:");
        getContentPane().add(lblNomeEmpresa);
        lblNomeEmpresa.setBounds(30, 190, 140, 30);
        getContentPane().add(txtNomeEmpresa);
        txtNomeEmpresa.setBounds(170, 190, 140, 30);

        lblValor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblValor.setText("Valor do benefício:");
        getContentPane().add(lblValor);
        lblValor.setBounds(40, 230, 130, 30);

        txtValorBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorBeneficioActionPerformed(evt);
            }
        });
        getContentPane().add(txtValorBeneficio);
        txtValorBeneficio.setBounds(170, 230, 140, 30);

        btnAlterarBeneficio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAlterarBeneficio.setText("ALTERAR");
        btnAlterarBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarBeneficioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterarBeneficio);
        btnAlterarBeneficio.setBounds(120, 280, 160, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("ALTERAR BENEFÍCIO DO FUNCIONÁRIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 50, 280, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 370, 370);

        setSize(new java.awt.Dimension(384, 377));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarBeneficioActionPerformed
        String nf, nb, nemp, vl;
        nf = txtNomeFuncionario.getText();
        nb = txtNomeBeneficio.getText();
        nemp = txtNomeEmpresa.getText();
        vl = txtValorBeneficio.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            
            PreparedStatement st = conectado.prepareStatement("update funcionario_beneficio set fk_nome_beneficio=?, fk_nome_empresa=?, valor=? where fk_nome_funcionario=?;");
            st.setString(1, nb);
            st.setString(2,nemp);
            st.setString(3, vl);
            st.setString(4, nf);

            st.executeUpdate();

            
            JOptionPane.showMessageDialog(null, "Beneficiário alterado com sucesso");
            dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: "+ex.getMessage());

        }
    }//GEN-LAST:event_btnAlterarBeneficioActionPerformed

    private void txtValorBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorBeneficioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorBeneficioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarFuncionarioBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarFuncionarioBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarFuncionarioBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarFuncionarioBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarFuncionarioBeneficiario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarBeneficio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNomeBeneficiario;
    private javax.swing.JLabel lblNomeBeneficio;
    private javax.swing.JLabel lblNomeEmpresa;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtNomeBeneficio;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtValorBeneficio;
    // End of variables declaration//GEN-END:variables
}
