
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gabri
 */
public class AlterarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form AlterarFuncionario
     */
    public AlterarFuncionario() {
        initComponents();
    }
    
    public AlterarFuncionario(String emp, String fun, String sen, String car, String depar) {
        initComponents();
        txtNomeEmpresa.setText(emp);
        txtNomeF.setText(fun);
        pswSenha.setText(sen);
        txtCargo.setText(car);
        txtDepartamento.setText(depar);
        txtNomeF.setEnabled(false);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeF = new javax.swing.JLabel();
        txtNomeF = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pswSenha = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        lblDepartamento = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        btnAltear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar dados do funcionário");
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(null);

        lblNomeF.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeF.setText("Nome do funcionário:");
        getContentPane().add(lblNomeF);
        lblNomeF.setBounds(20, 120, 150, 30);
        getContentPane().add(txtNomeF);
        txtNomeF.setBounds(170, 120, 140, 30);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblSenha.setText("Senha do funcionário:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(20, 160, 150, 30);
        getContentPane().add(pswSenha);
        pswSenha.setBounds(170, 160, 140, 30);

        lblCargo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblCargo.setText("Cargo do funcionário:");
        getContentPane().add(lblCargo);
        lblCargo.setBounds(20, 200, 150, 30);
        getContentPane().add(txtCargo);
        txtCargo.setBounds(170, 200, 140, 30);

        lblDepartamento.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblDepartamento.setText("Departamento:");
        getContentPane().add(lblDepartamento);
        lblDepartamento.setBounds(60, 240, 110, 30);
        getContentPane().add(txtDepartamento);
        txtDepartamento.setBounds(170, 240, 140, 30);

        btnAltear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAltear.setText("ALTERAR");
        btnAltear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltearActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltear);
        btnAltear.setBounds(120, 280, 160, 60);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Nome da empresa:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 80, 130, 30);
        getContentPane().add(txtNomeEmpresa);
        txtNomeEmpresa.setBounds(170, 80, 140, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("ALTERAR FUNCIONÁRIO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 30, 170, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 370, 370);

        setSize(new java.awt.Dimension(384, 377));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltearActionPerformed
         String emp,fun,sen,car,depar;
         emp = txtNomeEmpresa.getText();
         fun = txtNomeF.getText();
         sen = pswSenha.getText();
         car = txtCargo.getText();
         depar = txtDepartamento.getText();
         
         try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");
            
            PreparedStatement st = conectado.prepareStatement("UPDATE funcionario SET fk_nome_empresa=?, senha=?, cargo=?, departamento=? where nome_funcionario_id=?");
                st.setString(1, emp);
                st.setString(2, sen);
                st.setString(3, car);
                st.setString(4, depar);
                st.setString(5,fun);
                
                st.executeUpdate();
                txtNomeEmpresa.setText("");
                txtNomeF.setText("");
                pswSenha.setText("");
                txtCargo.setText("");
                txtDepartamento.setText("");
                
                JOptionPane.showMessageDialog(null, "Alteração no funcionário concluída com sucesso!");
                
             
         } catch(ClassNotFoundException | SQLException ex){
             JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
         
         }
       
         
    }//GEN-LAST:event_btnAltearActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblNomeF;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField pswSenha;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtNomeF;
    // End of variables declaration//GEN-END:variables
}
