
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gabri
 */
public class CadastrarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarFuncionario
     */
    public CadastrarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeFuncionario = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblSenhaFuncionario = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lblEmpresaF = new javax.swing.JLabel();
        txtEmpresaFuncionario = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        lblDepartamento = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        itmCadastrarFuncionario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar funcionário");
        getContentPane().setLayout(null);

        lblNomeFuncionario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeFuncionario.setText("Nome funcionário:");
        getContentPane().add(lblNomeFuncionario);
        lblNomeFuncionario.setBounds(10, 90, 130, 30);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(150, 90, 170, 30);

        lblSenhaFuncionario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblSenhaFuncionario.setText("Senha funcionário:");
        getContentPane().add(lblSenhaFuncionario);
        lblSenhaFuncionario.setBounds(10, 130, 130, 30);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(150, 130, 170, 30);

        lblEmpresaF.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblEmpresaF.setText("Nome Empresa:");
        getContentPane().add(lblEmpresaF);
        lblEmpresaF.setBounds(30, 170, 110, 30);
        getContentPane().add(txtEmpresaFuncionario);
        txtEmpresaFuncionario.setBounds(150, 170, 170, 30);

        lblCargo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblCargo.setText("Cargo funcionário:");
        getContentPane().add(lblCargo);
        lblCargo.setBounds(10, 250, 130, 30);

        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCargo);
        txtCargo.setBounds(150, 250, 170, 30);

        lblDepartamento.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblDepartamento.setText("Departamento: ");
        getContentPane().add(lblDepartamento);
        lblDepartamento.setBounds(30, 210, 110, 30);

        txtDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDepartamento);
        txtDepartamento.setBounds(150, 210, 170, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("CADASTRO FUNCIONÁRIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 30, 230, 25);

        itmCadastrarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itmCadastrarFuncionario.setText("CADASTRAR");
        itmCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(itmCadastrarFuncionario);
        itmCadastrarFuncionario.setBounds(130, 290, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 370, 370);

        setSize(new java.awt.Dimension(384, 377));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoActionPerformed

    private void txtDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartamentoActionPerformed

    private void itmCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarFuncionarioActionPerformed
         String nome, senha, empresa,departamento, cargo;
      
       nome = txtNome.getText();
       senha = txtSenha.getText();
       empresa = txtEmpresaFuncionario.getText();
       departamento = txtDepartamento.getText();
       cargo = txtCargo.getText();
       
       try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenBenefitspi", "root", "mysql123");
          
            System.out.println(nome);
            PreparedStatement st = conectado.prepareStatement("INSERT INTO funcionario (nome_funcionario_id, senha, fk_nome_empresa, departamento, cargo) values(?,?,?,?,?)");
            
            st.setString(1, nome);
            st.setString(2, senha);
            st.setString(3, empresa);
            st.setString(4, departamento);
            st.setString(5, cargo);
          
            
            st.executeUpdate(); 
            JOptionPane.showMessageDialog(null, "Funcionário cadastrado com sucesso!");

            txtNome.setText("");
            txtSenha.setText("");
            txtEmpresaFuncionario.setText("");
            txtDepartamento.setText("");
            txtCargo.setText("");
            
            txtNome.requestFocus();
       }catch(ClassNotFoundException ex){
           JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o driver JDBC");
       }catch(SQLException ex){
       if (ex.getMessage().contains("Duplicate entry")) { // se tiver um usuário duplicado, ele caí no if.
                JOptionPane.showMessageDialog(null, "Funcionário já cadastrado");
            } else {

                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados: " + ex.getMessage());
            }
       }
    }//GEN-LAST:event_itmCadastrarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton itmCadastrarFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblEmpresaF;
    private javax.swing.JLabel lblNomeFuncionario;
    private javax.swing.JLabel lblSenhaFuncionario;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtEmpresaFuncionario;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
