
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Gabri
 */
public class ExcluirBeneficioFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirBeneficioFuncionario
     */
    public ExcluirBeneficioFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeFuncionario = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        lblNomeBeneficio = new javax.swing.JLabel();
        txtNomeBeneficio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnExcluirBeneficio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Excluir benefício do funcionário");
        getContentPane().setLayout(null);

        lblNomeFuncionario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeFuncionario.setText("Nome funcionário:");
        getContentPane().add(lblNomeFuncionario);
        lblNomeFuncionario.setBounds(10, 100, 130, 30);

        txtNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeFuncionario);
        txtNomeFuncionario.setBounds(140, 100, 170, 30);

        lblNomeBeneficio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeBeneficio.setText("Nome Beneficio:");
        getContentPane().add(lblNomeBeneficio);
        lblNomeBeneficio.setBounds(20, 140, 120, 30);
        getContentPane().add(txtNomeBeneficio);
        txtNomeBeneficio.setBounds(140, 140, 170, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("EXCLUIR BENEFÍCIO DO FUNCIONÁRIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 270, 40);

        btnExcluirBeneficio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluirBeneficio.setText("EXCLUIR");
        btnExcluirBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirBeneficioActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluirBeneficio);
        btnExcluirBeneficio.setBounds(100, 190, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 320, 320);

        setSize(new java.awt.Dimension(334, 320));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFuncionarioActionPerformed

    private void btnExcluirBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirBeneficioActionPerformed
        String nomeF, beneficioF;
        nomeF = txtNomeFuncionario.getText();
        beneficioF = txtNomeBeneficio.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("DELETE FROM funcionario_beneficio WHERE fk_nome_funcionario = ? AND fk_nome_beneficio = ?");
            st.setString(1, nomeF);
            st.setString(2, beneficioF);

            int retorno = st.executeUpdate();
            if (retorno == 1) {
                JOptionPane.showMessageDialog(null, "Beneficio do funcionário excluído com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Beneficio do funcionário não existente");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluirBeneficioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirBeneficioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirBeneficioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirBeneficioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirBeneficioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirBeneficioFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirBeneficio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNomeBeneficio;
    private javax.swing.JLabel lblNomeFuncionario;
    private javax.swing.JTextField txtNomeBeneficio;
    private javax.swing.JTextField txtNomeFuncionario;
    // End of variables declaration//GEN-END:variables
}
