
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Gabri
 */
public class ListarBeneficio extends javax.swing.JFrame {

    /**
     * Creates new form ListarBeneficio
     */
    public ListarBeneficio() {
        initComponents();
    }

    private void carregarDados() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT * FROM beneficio;");

            ResultSet beneficio = st.executeQuery();

            DefaultTableModel tblModelo = (DefaultTableModel) tblListarBeneficio.getModel();

            tblModelo.setRowCount(0);

            while (beneficio.next()) {
                Object linha[] = {
                    beneficio.getString("nome_beneficio"),
                    beneficio.getString("tipo"),};
                tblModelo.addRow(linha);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suprote e informe o erro: " + ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarBeneficio = new javax.swing.JTable();
        lblBeneficio = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        txtBeneficio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar os benefícios");
        getContentPane().setLayout(null);

        tblListarBeneficio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListarBeneficio);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 140, 570, 360);

        lblBeneficio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblBeneficio.setText("Nome benefício:");
        getContentPane().add(lblBeneficio);
        lblBeneficio.setBounds(280, 80, 110, 40);

        lblTipo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTipo.setText("Tipo do benefício:");
        getContentPane().add(lblTipo);
        lblTipo.setBounds(10, 80, 130, 40);
        getContentPane().add(txtBeneficio);
        txtBeneficio.setBounds(390, 90, 140, 27);

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(540, 80, 100, 40);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Alimentício", "Locomoção", "Saúde", "Lazer" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipo);
        cmbTipo.setBounds(140, 90, 130, 27);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("LISTAGEM DE BENEFÍCIOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 30, 230, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 540);

        setSize(new java.awt.Dimension(673, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nb;
        nb = txtBeneficio.getText(); // pega todos os usuários

        if (nb.equals("")) { // Busca todos
            carregarDados();
            return; // exit - para a execução
        }

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT * FROM beneficio WHERE nome_beneficio = ?");
            st.setString(1, nb);
            ResultSet nbeneficio = st.executeQuery();
            DefaultTableModel tblModelo = (DefaultTableModel) tblListarBeneficio.getModel();
            tblModelo.setRowCount(0);
            while (nbeneficio.next()) {
                Object linha[] = {
                    nbeneficio.getString("nome_beneficio"),
                    nbeneficio.getString("tipo"),};
                tblModelo.addRow(linha);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entr em contato com o suporte e informe o erro: " + ex.getMessage());

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        String tp = cmbTipo.getSelectedItem().toString();

        if (tp.equals("Todos")) {
            carregarDados();
            return;
        }

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("select * from beneficio where tipo =?;");
            st.setString(1, tp);

            ResultSet beneficio = st.executeQuery();

            DefaultTableModel tblModelo = (DefaultTableModel) tblListarBeneficio.getModel();

            tblModelo.setRowCount(0);

            while (beneficio.next()) {
                Object linha[] = {
                    beneficio.getString("nome_beneficio"),
                    beneficio.getString("tipo"),};
                tblModelo.addRow(linha);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_cmbTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarBeneficio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBeneficio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable tblListarBeneficio;
    private javax.swing.JTextField txtBeneficio;
    // End of variables declaration//GEN-END:variables
}
