
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Gabri
 */
public class ListarEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form ListarEmpresa
     */
    public ListarEmpresa() {
        initComponents();
    }

    private void carregarDados() {

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT * FROM empresa");
            ResultSet empresa = st.executeQuery();
            DefaultTableModel tblModelo = (DefaultTableModel) tblListarEmpresa.getModel();
            tblModelo.setRowCount(0);
            while (empresa.next()) {
                Object linha[] = {
                    empresa.getString("nome_empresa_id"),
                    empresa.getString("ramo_atividade"),};
                tblModelo.addRow(linha);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entr em contato com o suporte e informe o erro: " + ex.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarEmpresa = new javax.swing.JTable();
        lblNomeEmpresa = new javax.swing.JLabel();
        cmbRamo = new javax.swing.JComboBox<>();
        lblRamo = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar as empresas");
        getContentPane().setLayout(null);

        tblListarEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Ramo "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListarEmpresa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 150, 570, 360);

        lblNomeEmpresa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeEmpresa.setText("Nome da empresa:");
        getContentPane().add(lblNomeEmpresa);
        lblNomeEmpresa.setBounds(250, 90, 130, 50);

        cmbRamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Aeria", "Alimentício", "Educação", "Financeiro", "Tecnologia", "Turístico", "Esportivo", "Saúde" }));
        cmbRamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRamoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbRamo);
        cmbRamo.setBounds(100, 100, 130, 27);

        lblRamo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblRamo.setText("Ramo:");
        getContentPane().add(lblRamo);
        lblRamo.setBounds(50, 100, 50, 30);
        getContentPane().add(txtNomeEmpresa);
        txtNomeEmpresa.setBounds(380, 100, 140, 27);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("LISTAGEM DAS EMPRESAS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 40, 230, 25);

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(530, 90, 100, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 550);

        setSize(new java.awt.Dimension(673, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRamoActionPerformed
        String re;
        re = cmbRamo.getSelectedItem().toString();

        if (re.equals("Todos")) {
            carregarDados();
            return;
        }

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT * FROM empresa WHERE ramo_atividade = ?");
            st.setString(1, re);
            ResultSet empresa = st.executeQuery();
            DefaultTableModel tblModelo = (DefaultTableModel) tblListarEmpresa.getModel();
            tblModelo.setRowCount(0);
            while (empresa.next()) {
                Object linha[] = {
                    empresa.getString("nome_empresa_id"),
                    empresa.getString("ramo_atividade"),};
                tblModelo.addRow(linha);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entr em contato com o suporte e informe o erro: " + ex.getMessage());

        }


    }//GEN-LAST:event_cmbRamoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String e;
        e = txtNomeEmpresa.getText();

        if (e.equals("")) {
            carregarDados();
            return;
        }

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT * FROM empresa WHERE nome_empresa_id = ?");
            st.setString(1, e);
            ResultSet empresa = st.executeQuery();
            DefaultTableModel tblModelo = (DefaultTableModel) tblListarEmpresa.getModel();
            tblModelo.setRowCount(0);
            while (empresa.next()) {
                Object linha[] = {
                    empresa.getString("nome_empresa_id"),
                    empresa.getString("ramo_atividade"),};
                tblModelo.addRow(linha);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entr em contato com o suporte e informe o erro: " + ex.getMessage());

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbRamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeEmpresa;
    private javax.swing.JLabel lblRamo;
    private javax.swing.JTable tblListarEmpresa;
    private javax.swing.JTextField txtNomeEmpresa;
    // End of variables declaration//GEN-END:variables
}
