
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gabri
 */
public class AlterarEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form AlterarSenhaEmpresa
     */
    public AlterarEmpresa() {
        initComponents();
    }
     public AlterarEmpresa(String emp,String sen, String ram) {
        initComponents();
        txtNomeEmpresa.setText(emp);
        pswSenhaEmpresa.setText(sen);
        txtRamo.setText(ram);
        txtNomeEmpresa.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pswSenhaEmpresa = new javax.swing.JTextField();
        lblRamo = new javax.swing.JLabel();
        txtRamo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar dados da empresa");
        getContentPane().setLayout(null);

        lblNome.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNome.setText("Nome da empresa:");
        getContentPane().add(lblNome);
        lblNome.setBounds(30, 90, 130, 30);
        getContentPane().add(txtNomeEmpresa);
        txtNomeEmpresa.setBounds(160, 90, 140, 30);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblSenha.setText("Senha da empresa:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(30, 170, 130, 30);
        getContentPane().add(pswSenhaEmpresa);
        pswSenhaEmpresa.setBounds(160, 170, 140, 30);

        lblRamo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblRamo.setText("Ramo da empresa:");
        getContentPane().add(lblRamo);
        lblRamo.setBounds(30, 130, 130, 30);
        getContentPane().add(txtRamo);
        txtRamo.setBounds(160, 130, 140, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("ALTERAR EMPRESA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 40, 170, 25);

        btnAlterar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(110, 220, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 350, 330);

        setSize(new java.awt.Dimension(364, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       String e, r, s;
        e = txtNomeEmpresa.getText();
        r = txtRamo.getText();
        s = pswSenhaEmpresa.getText();

     
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            
            PreparedStatement st = conectado.prepareStatement("update empresa set senha=?, ramo_atividade=? where nome_empresa_id=?;");
            st.setString(1, s);
            st.setString(2,r);
            st.setString(3, e);

            st.executeUpdate();

            
            JOptionPane.showMessageDialog(null, "Alterações feita com sucesso");
            dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: "+ex.getMessage());

        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRamo;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField pswSenhaEmpresa;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtRamo;
    // End of variables declaration//GEN-END:variables
}
