
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gabri
 */
public class CadatrarEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarEmpresa
     */
    public CadatrarEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pswSenha = new javax.swing.JTextField();
        lblRamo = new javax.swing.JLabel();
        txtRamo = new javax.swing.JTextField();
        btnCadastrarEmpresa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar empresa");
        getContentPane().setLayout(null);

        lblNome.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNome.setText("Nome da empresa:");
        getContentPane().add(lblNome);
        lblNome.setBounds(20, 100, 130, 30);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(160, 100, 140, 30);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblSenha.setText("Senha da empresa:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(20, 180, 130, 30);
        getContentPane().add(pswSenha);
        pswSenha.setBounds(160, 180, 140, 30);

        lblRamo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblRamo.setText("Ramo da empresa:");
        getContentPane().add(lblRamo);
        lblRamo.setBounds(20, 140, 130, 30);
        getContentPane().add(txtRamo);
        txtRamo.setBounds(160, 140, 140, 30);

        btnCadastrarEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrarEmpresa.setText("CADASTRAR");
        btnCadastrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarEmpresa);
        btnCadastrarEmpresa.setBounds(140, 230, 160, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("CADASTRAR EMPRESA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 50, 200, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 350, 350);

        setSize(new java.awt.Dimension(364, 357));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEmpresaActionPerformed
        String nome, ramo, senha;
        nome = txtNome.getText();
        ramo = txtRamo.getText();
        senha = pswSenha.getText();
        
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");
            PreparedStatement st = conectado.prepareStatement("INSERT INTO empresa (nome_Empresa_id, Ramo_atividade, senha) values (?,?,?)");
            st.setString(1, nome);
            st.setString(2, ramo);
            st.setString(3, senha);
            
            st.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Empresa cadastrado com sucesso!");
      
            txtNome.setText("");
            txtRamo.setText("");
            pswSenha.setText("");
            
        }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o driver JDBC");
        } catch (SQLException ex) {
            if (ex.getMessage().contains("Duplicate entry")) { // se tiver um usuário duplicado, ele caí no if.
                JOptionPane.showMessageDialog(null, "Empresa já cadastrado");
            } else {

                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados: " + ex.getMessage());
            }

        }
    }//GEN-LAST:event_btnCadastrarEmpresaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadatrarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadatrarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadatrarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadatrarEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadatrarEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRamo;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField pswSenha;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRamo;
    // End of variables declaration//GEN-END:variables
}
