
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gabri
 */
public class CadastrarBeneficioFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarBeneficioFuncionario
     */
    public CadastrarBeneficioFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeFuncionario = new javax.swing.JLabel();
        txtNomeF = new javax.swing.JTextField();
        lblNomeBeneficio = new javax.swing.JLabel();
        txtNomeBeneficio = new javax.swing.JTextField();
        lblEmpresaF = new javax.swing.JLabel();
        txtEmpresaFuncionario = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnBeneficioFuncionario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar benefício ao funcionário");
        getContentPane().setLayout(null);

        lblNomeFuncionario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeFuncionario.setText("Nome funcionário:");
        getContentPane().add(lblNomeFuncionario);
        lblNomeFuncionario.setBounds(30, 90, 130, 30);

        txtNomeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeF);
        txtNomeF.setBounds(170, 90, 170, 30);

        lblNomeBeneficio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeBeneficio.setText("Nome do beneficio:");
        getContentPane().add(lblNomeBeneficio);
        lblNomeBeneficio.setBounds(20, 130, 140, 30);
        getContentPane().add(txtNomeBeneficio);
        txtNomeBeneficio.setBounds(170, 130, 170, 30);

        lblEmpresaF.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblEmpresaF.setText("Nome da empresa:");
        getContentPane().add(lblEmpresaF);
        lblEmpresaF.setBounds(30, 170, 130, 30);
        getContentPane().add(txtEmpresaFuncionario);
        txtEmpresaFuncionario.setBounds(170, 170, 170, 30);

        lblValor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblValor.setText("Valor do benefício:");
        getContentPane().add(lblValor);
        lblValor.setBounds(30, 210, 130, 30);

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        getContentPane().add(txtValor);
        txtValor.setBounds(170, 210, 170, 30);

        btnBeneficioFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBeneficioFuncionario.setText("CADASTRAR");
        btnBeneficioFuncionario.setActionCommand("Cadastrar");
        btnBeneficioFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeneficioFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnBeneficioFuncionario);
        btnBeneficioFuncionario.setBounds(120, 260, 160, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("CADASTRO DO FUNCIONÁRIO AO BENEFÍCIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 320, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 370, 380);

        setSize(new java.awt.Dimension(384, 377));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void btnBeneficioFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeneficioFuncionarioActionPerformed
        String nome, beneficio, empresa, valor;
      
       nome = txtNomeF.getText();
       beneficio = txtNomeBeneficio.getText();
       empresa = txtEmpresaFuncionario.getText();
       valor = txtValor.getText();
       
       try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenBenefitspi", "root", "mysql123");
          
            System.out.println(nome);
            PreparedStatement st = conectado.prepareStatement("INSERT INTO funcionario_beneficio (fk_nome_funcionario, fk_nome_beneficio, fk_nome_empresa, valor) values(?,?,?,?)");
            
            st.setString(1, nome);
            st.setString(2, beneficio);
            st.setString(3, empresa);
            st.setString(4, valor);
            
          
            
            st.executeUpdate(); 
            JOptionPane.showMessageDialog(null, "Beneficio cadastrado ao funcionário com sucesso!");

            txtNomeF.setText("");
            txtNomeBeneficio.setText("");
            txtEmpresaFuncionario.setText("");
            txtValor.setText("");
           
            
            txtNomeF.requestFocus();
       }catch(ClassNotFoundException ex){
           JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o driver JDBC");
       }catch(SQLException ex){
       if (ex.getMessage().contains("Duplicate entry")) { // se tiver um usuário duplicado, ele caí no if.
                JOptionPane.showMessageDialog(null, "Funcionário já possuí esse benefício");
            } else {

                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados: " + ex.getMessage());
            }
       }
    
    }//GEN-LAST:event_btnBeneficioFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarBeneficioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarBeneficioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarBeneficioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarBeneficioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarBeneficioFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeneficioFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmpresaF;
    private javax.swing.JLabel lblNomeBeneficio;
    private javax.swing.JLabel lblNomeFuncionario;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtEmpresaFuncionario;
    private javax.swing.JTextField txtNomeBeneficio;
    private javax.swing.JTextField txtNomeF;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
