
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gabri
 */
public class CadastrarBeneficio extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarBeneficio
     */
    public CadastrarBeneficio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeBeneficio = new javax.swing.JLabel();
        txtNomeBeneficio = new javax.swing.JTextField();
        lblTipoBeneficio = new javax.swing.JLabel();
        txtTipoBeneficio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCriarBeneficio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar benefício");
        getContentPane().setLayout(null);

        lblNomeBeneficio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeBeneficio.setText("Nome do benefício:");
        getContentPane().add(lblNomeBeneficio);
        lblNomeBeneficio.setBounds(10, 100, 130, 30);

        txtNomeBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeBeneficioActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeBeneficio);
        txtNomeBeneficio.setBounds(140, 100, 160, 30);

        lblTipoBeneficio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTipoBeneficio.setText("Tipo do benefício:");
        getContentPane().add(lblTipoBeneficio);
        lblTipoBeneficio.setBounds(10, 140, 130, 30);

        txtTipoBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoBeneficioActionPerformed(evt);
            }
        });
        getContentPane().add(txtTipoBeneficio);
        txtTipoBeneficio.setBounds(140, 140, 160, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("CADASTRO DO BENEFÍCIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 50, 190, 20);

        btnCriarBeneficio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCriarBeneficio.setText("CADASTRAR");
        btnCriarBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarBeneficioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCriarBeneficio);
        btnCriarBeneficio.setBounds(90, 180, 160, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 320, 260);

        setSize(new java.awt.Dimension(334, 267));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeBeneficioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeBeneficioActionPerformed

    private void txtTipoBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoBeneficioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoBeneficioActionPerformed

    private void btnCriarBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarBeneficioActionPerformed
         String nome, tipo;

        nome = txtNomeBeneficio.getText();
        tipo = txtTipoBeneficio.getText();


        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");
            PreparedStatement st = conectado.prepareStatement("INSERT INTO beneficio(Nome_beneficio, tipo) values(?,?)");

            st.setString(1, nome);
            st.setString(2, tipo);

            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Benefício cadastrado com sucesso!");

            txtNomeBeneficio.setText("");
            txtTipoBeneficio.setText("");

            txtNomeBeneficio.requestFocus();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o Driver JDBC");
        } catch (SQLException ex) {
            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Benefício já cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCriarBeneficioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarBeneficio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarBeneficio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNomeBeneficio;
    private javax.swing.JLabel lblTipoBeneficio;
    private javax.swing.JTextField txtNomeBeneficio;
    private javax.swing.JTextField txtTipoBeneficio;
    // End of variables declaration//GEN-END:variables
}
