
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Gabri
 */
public class ListarFuncionarioBeneficiario extends javax.swing.JFrame {

    /**
     * Creates new form ListarFuncionarioBeneficiario
     */
    public ListarFuncionarioBeneficiario() {
        initComponents();
    }

    private void carregarDados() {

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT * FROM funcionario_beneficio");
            ResultSet funcionario = st.executeQuery();
            DefaultTableModel tblModelo = (DefaultTableModel) tblListarBeneficiario.getModel();
            tblModelo.setRowCount(0);
            while (funcionario.next()) {
                Object linha[] = {
                    funcionario.getString("fk_nome_funcionario"),
                    funcionario.getString("fk_nome_beneficio"),
                    funcionario.getString("fk_nome_empresa"),};
                tblModelo.addRow(linha);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entrar em contato com o suporte e informe o erro: " + ex.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarBeneficiario = new javax.swing.JTable();
        lblFuncionario = new javax.swing.JLabel();
        cmbF = new javax.swing.JComboBox<>();
        lblNomeBeneficio = new javax.swing.JLabel();
        txtNomeFun = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar funcionários com benefícios");
        getContentPane().setLayout(null);

        tblListarBeneficiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Benefício", "Empresa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListarBeneficiario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 140, 570, 360);

        lblFuncionario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblFuncionario.setText("Nome funcionário:");
        getContentPane().add(lblFuncionario);
        lblFuncionario.setBounds(250, 80, 130, 40);

        cmbF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Vale Transporte", "Vale Refeição", "Vale Alimentação", "Gympass", "Saúde", "Plano Dentário", "Vale Cultura" }));
        cmbF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFActionPerformed(evt);
            }
        });
        getContentPane().add(cmbF);
        cmbF.setBounds(110, 90, 130, 27);

        lblNomeBeneficio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeBeneficio.setText(" benefício:");
        getContentPane().add(lblNomeBeneficio);
        lblNomeBeneficio.setBounds(40, 80, 70, 40);
        getContentPane().add(txtNomeFun);
        txtNomeFun.setBounds(380, 90, 140, 27);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("LISTAGEM FUNCIONÁRIOS COM BENEFÍCIOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 30, 390, 25);

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(530, 80, 100, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 540);

        setSize(new java.awt.Dimension(673, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFActionPerformed
        String nbeneficio;
        nbeneficio = cmbF.getSelectedItem().toString();

        if (nbeneficio.equals("Todos")) {
            carregarDados();
            return;
        }

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT * FROM funcionario_beneficio WHERE fk_nome_beneficio = ?");
            st.setString(1, nbeneficio);
            ResultSet funcionario = st.executeQuery();
            DefaultTableModel tblModelo = (DefaultTableModel) tblListarBeneficiario.getModel();
            tblModelo.setRowCount(0);
            while (funcionario.next()) {
                Object linha[] = {
                    funcionario.getString("fk_nome_funcionario"),
                    funcionario.getString("fk_nome_empresa"),
                    funcionario.getString("fk_nome_beneficio"),};
                tblModelo.addRow(linha);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entr em contato com o suporte e informe o erro: " + ex.getMessage());

        }

    }//GEN-LAST:event_cmbFActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nf;
        nf = txtNomeFun.getText();

        if (nf.equals("")) {
            carregarDados();
            return;
        }

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT * FROM funcionario_beneficio WHERE fk_nome_funcionario = ?");
            st.setString(1, nf);
            ResultSet nfuncionario = st.executeQuery();
            DefaultTableModel tblModelo = (DefaultTableModel) tblListarBeneficiario.getModel();
            tblModelo.setRowCount(0);
            while (nfuncionario.next()) {
                Object linha[] = {
                    nfuncionario.getString("fk_nome_funcionario"),
                    nfuncionario.getString("fk_nome_beneficio"),
                    nfuncionario.getString("fk_nome_empresa"),};
                tblModelo.addRow(linha);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entr em contato com o suporte e informe o erro: " + ex.getMessage());

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarFuncionarioBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarFuncionarioBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarFuncionarioBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarFuncionarioBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarFuncionarioBeneficiario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblNomeBeneficio;
    private javax.swing.JTable tblListarBeneficiario;
    private javax.swing.JTextField txtNomeFun;
    // End of variables declaration//GEN-END:variables
}
