
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Gabri
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmpresa = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        lblNomeFuncionario = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pswSenhaFuncionario = new javax.swing.JPasswordField();
        cmbCargo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acesso ao sistema");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        lblEmpresa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblEmpresa.setText("Nome da Empresa:");
        getContentPane().add(lblEmpresa);
        lblEmpresa.setBounds(20, 100, 130, 30);
        getContentPane().add(txtNomeEmpresa);
        txtNomeEmpresa.setBounds(160, 100, 130, 30);

        lblNomeFuncionario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNomeFuncionario.setText("Nome funcionário:");
        getContentPane().add(lblNomeFuncionario);
        lblNomeFuncionario.setBounds(20, 140, 130, 30);
        getContentPane().add(txtNomeFuncionario);
        txtNomeFuncionario.setBounds(160, 140, 130, 30);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblSenha.setText("Senha Funcionário:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(20, 180, 130, 30);
        getContentPane().add(pswSenhaFuncionario);
        pswSenhaFuncionario.setBounds(160, 180, 130, 30);

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Gerente", "Esp em beneficios" }));
        getContentPane().add(cmbCargo);
        cmbCargo.setBounds(160, 220, 130, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 40, 80, 30);

        btnEntrar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(110, 260, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 350, 350);

        setSize(new java.awt.Dimension(364, 357));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String f = txtNomeFuncionario.getText();
        String s = pswSenhaFuncionario.getText();
        String e = txtNomeEmpresa.getText();

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT cargo FROM funcionario WHERE nome_funcionario_id = ? AND senha = ? AND fk_nome_empresa = ?;");
            st.setString(1, f);
            st.setString(2, s);
            st.setString(3, e);

            ResultSet resultado = st.executeQuery();

            if (resultado.next()) {

                String cargo = resultado.getString("cargo");
                dispose();
                new Menu(cargo).setVisible(true);
                //new Login().setVisible(false);

            } else {
                JOptionPane.showMessageDialog(null, "funcionário e/ou senha inválidos");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblNomeFuncionario;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPasswordField pswSenhaFuncionario;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtNomeFuncionario;
    // End of variables declaration//GEN-END:variables
}
