
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Gabri
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    public Menu(String cargo) {
        initComponents();

        if (cargo.equalsIgnoreCase("Administrador")) {

        } else if (cargo.equalsIgnoreCase("Gerente")) {
            mnuEmpresa.setEnabled(false);
            mnuFuncionario.setVisible(true);

        } else if(cargo.equalsIgnoreCase("Esp em beneficios")){
            mnuEmpresa.setEnabled(false);
            mnuFuncionario.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuEmpresa = new javax.swing.JMenu();
        itmCadastrarEmpresa = new javax.swing.JMenuItem();
        itmExcluirEmpresa = new javax.swing.JMenuItem();
        itmAlterarSenha = new javax.swing.JMenuItem();
        itmListarEmpresa = new javax.swing.JMenuItem();
        mnuFuncionario = new javax.swing.JMenu();
        itmCadastrarFuncionario = new javax.swing.JMenuItem();
        itmExcluir = new javax.swing.JMenuItem();
        itmAlterarFuncionario = new javax.swing.JMenuItem();
        itmListarFuncionarios = new javax.swing.JMenuItem();
        mnuBeneficios = new javax.swing.JMenu();
        itmCadastrarBeneficio = new javax.swing.JMenuItem();
        itmExcluirBeneficio = new javax.swing.JMenuItem();
        itmAlterarBeneficio = new javax.swing.JMenuItem();
        itmListarBeneficio = new javax.swing.JMenuItem();
        mnuFuncionarioBeneficio = new javax.swing.JMenu();
        itmCadastrarBeneficioF = new javax.swing.JMenuItem();
        itmExcluirBeneficioFuncionário = new javax.swing.JMenuItem();
        itmAlterarFuncionarioBeneficio = new javax.swing.JMenuItem();
        itmFuncionarioBeneficio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Administrativo");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("GOLDENBENEFITS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 80, 220, 32);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 360, 260);

        mnuEmpresa.setText("Empresa");

        itmCadastrarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/adicionar.png"))); // NOI18N
        itmCadastrarEmpresa.setText("Cadastrar");
        itmCadastrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarEmpresaActionPerformed(evt);
            }
        });
        mnuEmpresa.add(itmCadastrarEmpresa);

        itmExcluirEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/lixeira.png"))); // NOI18N
        itmExcluirEmpresa.setText("Excluir ");
        itmExcluirEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirEmpresaActionPerformed(evt);
            }
        });
        mnuEmpresa.add(itmExcluirEmpresa);

        itmAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/alterar.png"))); // NOI18N
        itmAlterarSenha.setText("Alterar");
        itmAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarSenhaActionPerformed(evt);
            }
        });
        mnuEmpresa.add(itmAlterarSenha);

        itmListarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/listagem.png"))); // NOI18N
        itmListarEmpresa.setText("Listar");
        itmListarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarEmpresaActionPerformed(evt);
            }
        });
        mnuEmpresa.add(itmListarEmpresa);

        jMenuBar1.add(mnuEmpresa);

        mnuFuncionario.setText("Funcionário");

        itmCadastrarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/adicionar-usuario.png"))); // NOI18N
        itmCadastrarFuncionario.setText("Cadastrar");
        itmCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionario.add(itmCadastrarFuncionario);

        itmExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/lixeira.png"))); // NOI18N
        itmExcluir.setText("Excluir");
        itmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirActionPerformed(evt);
            }
        });
        mnuFuncionario.add(itmExcluir);

        itmAlterarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/alterar.png"))); // NOI18N
        itmAlterarFuncionario.setText("Alterar");
        itmAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionario.add(itmAlterarFuncionario);

        itmListarFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/listagem.png"))); // NOI18N
        itmListarFuncionarios.setText("Listar");
        itmListarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarFuncionariosActionPerformed(evt);
            }
        });
        mnuFuncionario.add(itmListarFuncionarios);

        jMenuBar1.add(mnuFuncionario);

        mnuBeneficios.setText("Benefícios");

        itmCadastrarBeneficio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/adicionar.png"))); // NOI18N
        itmCadastrarBeneficio.setText("Cadastrar");
        itmCadastrarBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarBeneficioActionPerformed(evt);
            }
        });
        mnuBeneficios.add(itmCadastrarBeneficio);

        itmExcluirBeneficio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/lixeira.png"))); // NOI18N
        itmExcluirBeneficio.setText("Excluir");
        itmExcluirBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirBeneficioActionPerformed(evt);
            }
        });
        mnuBeneficios.add(itmExcluirBeneficio);

        itmAlterarBeneficio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/alterar.png"))); // NOI18N
        itmAlterarBeneficio.setText("Alterar");
        itmAlterarBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarBeneficioActionPerformed(evt);
            }
        });
        mnuBeneficios.add(itmAlterarBeneficio);

        itmListarBeneficio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/listagem.png"))); // NOI18N
        itmListarBeneficio.setText("Listar");
        itmListarBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarBeneficioActionPerformed(evt);
            }
        });
        mnuBeneficios.add(itmListarBeneficio);

        jMenuBar1.add(mnuBeneficios);

        mnuFuncionarioBeneficio.setText("Funcionário Beneficiário");

        itmCadastrarBeneficioF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/adicionar-usuario.png"))); // NOI18N
        itmCadastrarBeneficioF.setText("Cadastrar");
        itmCadastrarBeneficioF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarBeneficioFActionPerformed(evt);
            }
        });
        mnuFuncionarioBeneficio.add(itmCadastrarBeneficioF);

        itmExcluirBeneficioFuncionário.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/lixeira.png"))); // NOI18N
        itmExcluirBeneficioFuncionário.setText("Excluir");
        itmExcluirBeneficioFuncionário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirBeneficioFuncionárioActionPerformed(evt);
            }
        });
        mnuFuncionarioBeneficio.add(itmExcluirBeneficioFuncionário);

        itmAlterarFuncionarioBeneficio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/alterar.png"))); // NOI18N
        itmAlterarFuncionarioBeneficio.setText("Alterar");
        itmAlterarFuncionarioBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarFuncionarioBeneficioActionPerformed(evt);
            }
        });
        mnuFuncionarioBeneficio.add(itmAlterarFuncionarioBeneficio);

        itmFuncionarioBeneficio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/usuario-final.png"))); // NOI18N
        itmFuncionarioBeneficio.setText("Listar");
        itmFuncionarioBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmFuncionarioBeneficioActionPerformed(evt);
            }
        });
        mnuFuncionarioBeneficio.add(itmFuncionarioBeneficio);

        jMenuBar1.add(mnuFuncionarioBeneficio);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(368, 284));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadastrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarEmpresaActionPerformed
        new CadatrarEmpresa().setVisible(true);
    }//GEN-LAST:event_itmCadastrarEmpresaActionPerformed

    private void itmCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarFuncionarioActionPerformed
        new CadastrarFuncionario().setVisible(true);
    }//GEN-LAST:event_itmCadastrarFuncionarioActionPerformed

    private void itmExcluirEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirEmpresaActionPerformed
        String nome;

        nome = JOptionPane.showInputDialog("Empresa a excluir: ");

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("delete from empresa where nome_empresa_id = ?");
            st.setString(1, nome);

            int retorno = st.executeUpdate();
            if (retorno == 1) {
                JOptionPane.showMessageDialog(null, "Empresa excluída com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Empresa não existe");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmExcluirEmpresaActionPerformed

    private void itmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirActionPerformed
        String nome;

        nome = JOptionPane.showInputDialog("Funcionário a excluir: ");

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("delete from funcionario where nome_funcionario_id = ?");
            st.setString(1, nome);

            int retorno = st.executeUpdate();
            if (retorno == 1) {
                JOptionPane.showMessageDialog(null, "Funcionário excluída com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Funcionário não existe");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmExcluirActionPerformed

    private void itmCadastrarBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarBeneficioActionPerformed
        new CadastrarBeneficio().setVisible(true);
    }//GEN-LAST:event_itmCadastrarBeneficioActionPerformed

    private void itmExcluirBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirBeneficioActionPerformed
        String b;

        b = JOptionPane.showInputDialog("Beneficio a excluir: ");

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("delete from beneficio where nome_beneficio = ?");
            st.setString(1, b);

            int retorno = st.executeUpdate();
            if (retorno == 1) {
                JOptionPane.showMessageDialog(null, "Beneficio excluída com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Beneficio não existente");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_itmExcluirBeneficioActionPerformed

    private void itmCadastrarBeneficioFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarBeneficioFActionPerformed
        new CadastrarBeneficioFuncionario().setVisible(true);
    }//GEN-LAST:event_itmCadastrarBeneficioFActionPerformed

    private void itmExcluirBeneficioFuncionárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirBeneficioFuncionárioActionPerformed
        new ExcluirBeneficioFuncionario().setVisible(true);
    }//GEN-LAST:event_itmExcluirBeneficioFuncionárioActionPerformed

    private void itmAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarSenhaActionPerformed

        String e;
        e = JOptionPane.showInputDialog("Empresa a alterar: ");
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT * FROM empresa WHERE nome_empresa_id = ?");
            st.setString(1, e);
            ResultSet empresa = st.executeQuery();

            if (empresa.next()) {

                String emp, sen, ram;
                emp = empresa.getString("nome_empresa_id");
                sen = empresa.getString("senha");
                ram = empresa.getString("ramo_atividade");
                new AlterarEmpresa(emp, sen, ram).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Empresa não encontrada");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmAlterarSenhaActionPerformed

    private void itmListarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarEmpresaActionPerformed
        new ListarEmpresa().setVisible(true);
    }//GEN-LAST:event_itmListarEmpresaActionPerformed

    private void itmListarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarFuncionariosActionPerformed
        new ListarFuncionarios().setVisible(true);
    }//GEN-LAST:event_itmListarFuncionariosActionPerformed

    private void itmListarBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarBeneficioActionPerformed
        new ListarBeneficio().setVisible(true);
    }//GEN-LAST:event_itmListarBeneficioActionPerformed

    private void itmAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarFuncionarioActionPerformed
        String f;
        f = JOptionPane.showInputDialog("Qual funcionário deseja alterar: ");
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT * FROM funcionario WHERE nome_funcionario_id = ?");
            st.setString(1, f);
            ResultSet funcionario = st.executeQuery();

            if (funcionario.next()) {
                String emp, fun, sen, car, depar;
                emp = funcionario.getString("fk_nome_empresa");
                fun = funcionario.getString("nome_funcionario_id");
                sen = funcionario.getString("senha");
                car = funcionario.getString("cargo");
                depar = funcionario.getString("departamento");
                new AlterarFuncionario(emp, fun, sen, car, depar).setVisible(true);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_itmAlterarFuncionarioActionPerformed

    private void itmAlterarBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarBeneficioActionPerformed
        String b;
        b = JOptionPane.showInputDialog("Benefício que você deseja alterar: ");
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT * FROM beneficio WHERE nome_beneficio= ?");
            st.setString(1, b);
            ResultSet beneficio = st.executeQuery();

            if (beneficio.next()) {

                String ben, tipo;
                ben = beneficio.getString("nome_beneficio");
                tipo = beneficio.getString("tipo");
                new AlterarBeneficio(ben, tipo).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "beneficio não encontrado");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmAlterarBeneficioActionPerformed

    private void itmAlterarFuncionarioBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarFuncionarioBeneficioActionPerformed
        String fb;
        fb = JOptionPane.showInputDialog("Funcionário que deseja alterar o benefício: ");
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/goldenbenefitspi", "root", "mysql123");

            PreparedStatement st = conectado.prepareStatement("SELECT * FROM funcionario_beneficio WHERE fk_nome_funcionario= ?");
            st.setString(1, fb);
            ResultSet fbeneficio = st.executeQuery();

            if (fbeneficio.next()) {
                String fknome, fkben, fkemp, valor;
                fknome = fbeneficio.getString("fk_nome_funcionario");
                fkben = fbeneficio.getString("fk_nome_beneficio");
                fkemp = fbeneficio.getString("fk_nome_empresa");
                valor = fbeneficio.getString("valor");
                new AlterarFuncionarioBeneficiario(fknome, fkben, fkemp, valor).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "beneficio não encontrado");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmAlterarFuncionarioBeneficioActionPerformed

    private void itmFuncionarioBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmFuncionarioBeneficioActionPerformed
        new ListarFuncionarioBeneficiario().setVisible(true);
    }//GEN-LAST:event_itmFuncionarioBeneficioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterarBeneficio;
    private javax.swing.JMenuItem itmAlterarFuncionario;
    private javax.swing.JMenuItem itmAlterarFuncionarioBeneficio;
    private javax.swing.JMenuItem itmAlterarSenha;
    private javax.swing.JMenuItem itmCadastrarBeneficio;
    private javax.swing.JMenuItem itmCadastrarBeneficioF;
    private javax.swing.JMenuItem itmCadastrarEmpresa;
    private javax.swing.JMenuItem itmCadastrarFuncionario;
    private javax.swing.JMenuItem itmExcluir;
    private javax.swing.JMenuItem itmExcluirBeneficio;
    private javax.swing.JMenuItem itmExcluirBeneficioFuncionário;
    private javax.swing.JMenuItem itmExcluirEmpresa;
    private javax.swing.JMenuItem itmFuncionarioBeneficio;
    private javax.swing.JMenuItem itmListarBeneficio;
    private javax.swing.JMenuItem itmListarEmpresa;
    private javax.swing.JMenuItem itmListarFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuBeneficios;
    private javax.swing.JMenu mnuEmpresa;
    private javax.swing.JMenu mnuFuncionario;
    private javax.swing.JMenu mnuFuncionarioBeneficio;
    // End of variables declaration//GEN-END:variables
}
